[tool.poetry]
name = "template for poetry2nix"
version = "0.7.0"
description = "A basic toml file"
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
